package com.gateway.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.Map;

/**
 * Order entity representing a merchant's sales order.
 * Orders are created before payment processing and serve as containers for payment information.
 * Each order belongs to a specific merchant and tracks the amount to be paid.
 * Status can be: created, processing, success, or failed (based on payment status).
 */
@Entity
@Table(name = "orders")
public class Order {

    /**
     * Unique order identifier (format: order_XXXXXXXXXXXXXXXX).
     * Primary key generated by IdGenerator with collision detection.
     */
    @Id
    private String id;

    /**
     * The merchant who created this order.
     * Foreign key reference; lazily fetched to optimize queries.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_id", nullable = false)
    private Merchant merchant;

    /**
     * Order amount in paise (smallest currency unit).
     * Minimum value enforced: 100 paise (1 INR).
     */
    @Column(nullable = false)
    private Integer amount;

    /**
     * Currency code for this order (e.g., "INR").
     * Defaults to "INR" if not specified.
     */
    @Column(length = 3, nullable = false)
    private String currency = "INR";

    /**
     * Merchant's receipt identifier or reference for this order.
     * Optional field for merchant record-keeping.
     */
    @Column(length = 255)
    private String receipt;

    /**
     * Arbitrary merchant metadata and notes stored as JSON.
     * Can contain custom fields like customer details, product info, etc.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> notes;

    /**
     * Current status of the order: created, processing, success, or failed.
     * Defaults to "created" on creation.
     * Updated based on associated payment statuses.
     */
    @Column(length = 20, nullable = false)
    private String status = "created";

    /**
     * Timestamp when the order was created (auto-populated on INSERT).
     */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /**
     * Timestamp when the order was last updated (auto-populated on INSERT/UPDATE).
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public Order() {
    }

    public Order(String id, Merchant merchant, Integer amount, String currency, String receipt,
                 Map<String, Object> notes, String status, Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.merchant = merchant;
        this.amount = amount;
        this.currency = currency;
        this.receipt = receipt;
        this.notes = notes;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @PrePersist
    public void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.currency == null) {
            this.currency = "INR";
        }
        if (this.status == null) {
            this.status = "created";
        }
    }

    @PreUpdate
    public void onUpdate() {
        this.updatedAt = Instant.now();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Merchant getMerchant() {
        return merchant;
    }

    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getReceipt() {
        return receipt;
    }

    public void setReceipt(String receipt) {
        this.receipt = receipt;
    }

    public Map<String, Object> getNotes() {
        return notes;
    }

    public void setNotes(Map<String, Object> notes) {
        this.notes = notes;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
