package com.gateway.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * Payment entity representing a payment attempt against an order.
 * Tracks payment method, amount, status, and sensitive card/UPI information.
 * Card numbers are NEVER stored; only the network type and last 4 digits are retained for security.
 * Status can be: processing, success, or failed.
 */
@Entity
@Table(name = "payments")
public class Payment {

    /**
     * Unique payment identifier (format: pay_XXXXXXXXXXXXXXXX).
     * Primary key generated by IdGenerator with collision detection.
     */
    @Id
    private String id;

    /**
     * The order this payment is being applied to.
     * Foreign key reference; lazily fetched to optimize queries.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /**
     * The merchant who initiated this payment.
     * Foreign key reference; lazily fetched to optimize queries.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_id", nullable = false)
    private Merchant merchant;

    /**
     * Payment amount in paise.
     * Typically matches the order amount (can differ in rare cases).
     */
    @Column(nullable = false)
    private Integer amount;

    /**
     * Currency code for this payment (e.g., "INR").
     * Should match the associated order's currency.
     */
    @Column(length = 3, nullable = false)
    private String currency = "INR";

    /**
     * Payment method: "upi" for UPI/VPA-based payments, "card" for credit/debit cards.
     */
    @Column(length = 20, nullable = false)
    private String method;

    /**
     * Current status of the payment: processing, success, or failed.
     * Defaults to "processing" on creation.
     */
    @Column(length = 20, nullable = false)
    private String status = "created";

    /**
     * Virtual Payment Address for UPI payments.
     * Format: username@bankname (e.g., user@upi)
     * Populated only when method is "upi".
     */
    @Column(length = 255)
    private String vpa;

    /**
     * Card network/brand detected from card number (visa, mastercard, amex, rupay).
     * Populated only when method is "card".
     */
    @Column(name = "card_network", length = 20)
    private String cardNetwork;

    /**
     * Last 4 digits of the card number.
     * Stored for user convenience; the full card number is NEVER persisted.
     * Populated only when method is "card".
     */
    @Column(name = "card_last4", length = 4)
    private String cardLast4;

    /**
     * Error code if the payment failed.
     * Examples: INVALID_VPA, INVALID_CARD, INSUFFICIENT_FUNDS, NETWORK_ERROR.
     * Null for successful payments.
     */
    @Column(name = "error_code", length = 50)
    private String errorCode;

    /**
     * Human-readable error message if the payment failed.
     * Provides context about why the payment was rejected.
     * Null for successful payments.
     */
    @Column(name = "error_description")
    private String errorDescription;

    /**
     * Timestamp when the payment was created (auto-populated on INSERT).
     */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /**
     * Timestamp when the payment was last updated (auto-populated on INSERT/UPDATE).
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public Payment() {
    }

    public Payment(String id, Order order, Merchant merchant, Integer amount, String currency, String method,
                   String status, String vpa, String cardNetwork, String cardLast4, String errorCode,
                   String errorDescription, Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.order = order;
        this.merchant = merchant;
        this.amount = amount;
        this.currency = currency;
        this.method = method;
        this.status = status;
        this.vpa = vpa;
        this.cardNetwork = cardNetwork;
        this.cardLast4 = cardLast4;
        this.errorCode = errorCode;
        this.errorDescription = errorDescription;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @PrePersist
    public void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.currency == null) {
            this.currency = "INR";
        }
        if (this.status == null) {
            this.status = "created";
        }
    }

    @PreUpdate
    public void onUpdate() {
        this.updatedAt = Instant.now();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public Merchant getMerchant() {
        return merchant;
    }

    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getVpa() {
        return vpa;
    }

    public void setVpa(String vpa) {
        this.vpa = vpa;
    }

    public String getCardNetwork() {
        return cardNetwork;
    }

    public void setCardNetwork(String cardNetwork) {
        this.cardNetwork = cardNetwork;
    }

    public String getCardLast4() {
        return cardLast4;
    }

    public void setCardLast4(String cardLast4) {
        this.cardLast4 = cardLast4;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorDescription() {
        return errorDescription;
    }

    public void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
